version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://${DOMAIN}
      - SIGNUPS_ALLOWED=${ALLOW_SIGNUPS:-false}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_FROM=${SMTP_FROM:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURITY=${SMTP_SECURITY:-starttls}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
    volumes:
      - ${DATA_DIR:-/var/lib/nestos/plugins/vaultwarden}/data:/data
    ports:
      - '${PORT:-8100}:80'
    networks:
      - nestos
